import type {Stock} from "@/views/stock-search/StockSearch.tsx";

export const mockStockResults: Stock[] = [
    {
        exchange: "NMS",
        shortname: "Apple Inc.",
        quoteType: "EQUITY",
        symbol: "AAPL",
        index: "quotes",
        score: 17282500,
        typeDisp: "Equity",
        longname: "Apple Inc.",
        exchDisp: "NASDAQ",
        sector: "Technology",
        sectorDisp: "Technology",
        industry: "Consumer Electronics",
        industryDisp: "Consumer Electronics",
        dispSecIndFlag: true,
        isYahooFinance: true
    },
    {
        exchange: "NMS",
        shortname: "Tesla, Inc.",
        quoteType: "EQUITY",
        symbol: "TSLA",
        index: "quotes",
        score: 15678900,
        typeDisp: "Equity",
        longname: "Tesla, Inc.",
        exchDisp: "NASDAQ",
        sector: "Consumer Cyclical",
        sectorDisp: "Consumer Cyclical",
        industry: "Auto Manufacturers",
        industryDisp: "Auto Manufacturers",
        dispSecIndFlag: true,
        isYahooFinance: true
    },
    {
        exchange: "NMS",
        shortname: "Microsoft Corp.",
        quoteType: "EQUITY",
        symbol: "MSFT",
        index: "quotes",
        score: 14567800,
        typeDisp: "Equity",
        longname: "Microsoft Corporation",
        exchDisp: "NASDAQ",
        sector: "Technology",
        sectorDisp: "Technology",
        industry: "Software—Infrastructure",
        industryDisp: "Software—Infrastructure",
        dispSecIndFlag: true,
        isYahooFinance: true
    },
    {
        exchange: "NMS",
        shortname: "Amazon.com, Inc.",
        quoteType: "EQUITY",
        symbol: "AMZN",
        index: "quotes",
        score: 13456700,
        typeDisp: "Equity",
        longname: "Amazon.com, Inc.",
        exchDisp: "NASDAQ",
        sector: "Consumer Cyclical",
        sectorDisp: "Consumer Cyclical",
        industry: "Internet Retail",
        industryDisp: "Internet Retail",
        dispSecIndFlag: true,
        isYahooFinance: true
    },
    {
        exchange: "NMS",
        shortname: "Alphabet Inc.",
        quoteType: "EQUITY",
        symbol: "GOOGL",
        index: "quotes",
        score: 12345600,
        typeDisp: "Equity",
        longname: "Alphabet Inc.",
        exchDisp: "NASDAQ",
        sector: "Communication Services",
        sectorDisp: "Communication Services",
        industry: "Internet Content & Information",
        industryDisp: "Internet Content & Information",
        dispSecIndFlag: true,
        isYahooFinance: true
    },
    {
        exchange: "NMS",
        shortname: "Meta Platforms, Inc.",
        quoteType: "EQUITY",
        symbol: "META",
        index: "quotes",
        score: 11234500,
        typeDisp: "Equity",
        longname: "Meta Platforms, Inc.",
        exchDisp: "NASDAQ",
        sector: "Communication Services",
        sectorDisp: "Communication Services",
        industry: "Internet Content & Information",
        industryDisp: "Internet Content & Information",
        dispSecIndFlag: true,
        isYahooFinance: true
    }
];
